version: '3.9'

services:
  app_ui:
    image: eventapp_ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - 3000:3000
    restart: always
    user: root
    environment:
      NODE_ENV: "dev"